"""initial migration

Revision ID: 0e03decda005
Revises: 
Create Date: 2025-09-03 13:50:21.251927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e03decda005'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('img', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.Column('picture', sa.String(), nullable=True),
    sa.Column('intro', sa.String(), nullable=True),
    sa.Column('ac_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name=op.f('fk_admins_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(), nullable=False),
    sa.Column('open_24hr', sa.Boolean(), nullable=False),
    sa.Column('allow_email', sa.Boolean(), nullable=False),
    sa.Column('chome', sa.Integer(), nullable=True),
    sa.Column('block', sa.Integer(), nullable=True),
    sa.Column('building_number', sa.Integer(), nullable=True),
    sa.Column('building_name', sa.String(), nullable=True),
    sa.Column('floor', sa.String(), nullable=True),
    sa.Column('room', sa.String(), nullable=True),
    sa.Column('post_code', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name=op.f('fk_businesses_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('travelers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name=op.f('fk_travelers_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_industries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('industry_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_business_industries_business_id_businesses')),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], name=op.f('fk_business_industries_industry_id_industries')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_industries')
    op.drop_table('travelers')
    op.drop_table('businesses')
    op.drop_table('admins')
    op.drop_table('users')
    op.drop_table('industries')
    # ### end Alembic commands ###
