"""create a neighbourhood table

Revision ID: 1f86563009a3
Revises: f846a0089f4c
Create Date: 2025-09-05 17:25:08.549516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f86563009a3'
down_revision = 'f846a0089f4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('neighbourhoods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('img', sa.String(), nullable=True),
    sa.Column('intro', sa.String(), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_neighbourhoods_city_id_cities')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('neighbourhood_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_businesses_neighbourhood_id_neighbourhoods'), 'neighbourhoods', ['neighbourhood_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_businesses_neighbourhood_id_neighbourhoods'), type_='foreignkey')
        batch_op.drop_column('neighbourhood_id')

    op.drop_table('neighbourhoods')
    # ### end Alembic commands ###
