"""create business operating hour exceptions table

Revision ID: 293f0a7afa35
Revises: 7bd68ea3cb8c
Create Date: 2025-09-04 10:38:05.640077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '293f0a7afa35'
down_revision = '7bd68ea3cb8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_hour_exceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('opening_time', sa.Time(), nullable=True),
    sa.Column('closing_time', sa.Time(), nullable=True),
    sa.Column('closes_next_day', sa.Boolean(), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_business_hour_exceptions_business_id_businesses')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_hour_exceptions')
    # ### end Alembic commands ###
