"""add traveler table

Revision ID: 30c9b33e518a
Revises: dcab51fa8440
Create Date: 2025-09-03 10:21:49.709605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30c9b33e518a'
down_revision = 'dcab51fa8440'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('travelers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name=op.f('fk_travelers_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('travelers')
    # ### end Alembic commands ###
