"""add city table

Revision ID: 7a0ba4d02129
Revises: 7faae71b49e2
Create Date: 2025-09-05 14:38:03.086464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a0ba4d02129'
down_revision = '7faae71b49e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_name', sa.String(), nullable=True),
    sa.Column('city_img', sa.String(), nullable=True),
    sa.Column('population', sa.String(), nullable=True),
    sa.Column('capital_city', sa.Boolean(), nullable=True),
    sa.Column('prefecture_capital', sa.Boolean(), nullable=True),
    sa.Column('city_intro', sa.String(), nullable=True),
    sa.Column('prefecture_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prefecture_id'], ['prefectures.id'], name=op.f('fk_cities_prefecture_id_prefectures')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cities')
    # ### end Alembic commands ###
