"""update prefecture and business tables

Revision ID: 7faae71b49e2
Revises: df37b4c8f534
Create Date: 2025-09-05 13:19:06.098063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7faae71b49e2'
down_revision = 'df37b4c8f534'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prefecture_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_businesses_prefecture_id_prefectures'), 'prefectures', ['prefecture_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_businesses_prefecture_id_prefectures'), type_='foreignkey')
        batch_op.drop_column('prefecture_id')

    # ### end Alembic commands ###
