"""create business table

Revision ID: 9a0ff01d32b6
Revises: 30c9b33e518a
Create Date: 2025-09-03 11:13:31.677759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a0ff01d32b6'
down_revision = '30c9b33e518a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(), nullable=False),
    sa.Column('open_24hr', sa.Boolean(), nullable=False),
    sa.Column('allow_email', sa.Boolean(), nullable=False),
    sa.Column('chome', sa.Integer(), nullable=True),
    sa.Column('block', sa.Integer(), nullable=True),
    sa.Column('building_number', sa.Integer(), nullable=True),
    sa.Column('building_name', sa.String(), nullable=True),
    sa.Column('floor', sa.String(), nullable=True),
    sa.Column('room', sa.String(), nullable=True),
    sa.Column('post_code', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name=op.f('fk_businesses_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('businesses')
    # ### end Alembic commands ###
