"""update prefecture table logic

Revision ID: df37b4c8f534
Revises: e694cafb179e
Create Date: 2025-09-05 12:47:28.515864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df37b4c8f534'
down_revision = 'e694cafb179e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prefectures', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_prefecture_name', ['prefecture_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prefectures', schema=None) as batch_op:
        batch_op.drop_constraint('unique_prefecture_name', type_='unique')

    # ### end Alembic commands ###
