"""add a prefecture table

Revision ID: e694cafb179e
Revises: 571744dac58b
Create Date: 2025-09-05 12:22:04.489733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e694cafb179e'
down_revision = '571744dac58b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prefectures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prefecture_name', sa.String(), nullable=False),
    sa.Column('kanji', sa.String(), nullable=True),
    sa.Column('prefecture_img', sa.String(), nullable=True),
    sa.Column('prefecture_intro', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prefecture_name'),
    sa.UniqueConstraint('prefecture_name', name='unique_prefecture_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prefectures')
    # ### end Alembic commands ###
