"""update business and city relationships

Revision ID: f846a0089f4c
Revises: 7a0ba4d02129
Create Date: 2025-09-05 14:48:43.145942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f846a0089f4c'
down_revision = '7a0ba4d02129'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_businesses_city_id_cities'), 'cities', ['city_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_businesses_city_id_cities'), type_='foreignkey')
        batch_op.drop_column('city_id')

    # ### end Alembic commands ###
